ShoppingCartMVC/Models/tblRefund.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ShoppingCartMVC.Models
{
    public class tblRefund
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RefundId { get; set; }
        public string EmailID { get; set; }
        public int OrderId { get; set; }
        public virtual ICollection<tblOrder> tblOrders { get; set; }
        public DateTime RefundRequestDate { get; set; }
        public string RefundReason { get; set; }
        public string Image { get; set; }
        public string RefundStatus { get; set; }

        public string checkStatus()
        {
            string sts = "";
            if (RefundStatus == "Successful")
            {
                sts = "Refund Complete";
            }
            else if (RefundStatus == "Unsuccessful")
            {
                sts = "Refund Not Cleared";
            }
            else
            {
                sts = "Refund Requested";
            }
            return sts;
        }
    }
}

ShoppingCartMVC/Controllers/tblRefundsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using ShoppingCartMVC.Models;

namespace ShoppingCartMVC.Controllers
{
    public class tblRefundsController : Controller
    {
        private dbOnlineStoreEntities db = new dbOnlineStoreEntities();

        // GET: tblRefunds
        public ActionResult Index()
        {
            return View(db.tblRefunds.ToList());
        }

        // GET: tblRefunds/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRefund tblRefund = db.tblRefunds.Find(id);
            if (tblRefund == null)
            {
                return HttpNotFound();
            }
            return View(tblRefund);
        }

        // GET: tblRefunds/Create
        public ActionResult Create(int orderId)
        {
            var order = db.tblOrders.FirstOrDefault(o => o.OrderId == orderId);

            var tblRefund = new tblRefund
            {
                OrderId = orderId
            };

            tblRefund.EmailID = order.TblInvoice.TblUser.Email;
            TempData["email"] = tblRefund.EmailID;

            List<tblOrder> list = db.tblOrders.ToList();
            ViewBag.OrderList = new SelectList(list, "OrderId", "OrderId");

            return View(tblRefund);


        }

        // POST: tblRefunds/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "RefundId,EmailID,OrderId,RefundRequestDate,RefundReason,Image,RefundStatus")] tblRefund tblRefund, HttpPostedFileBase Image, int orderId)
        {
            List<tblOrder> list = db.tblOrders.ToList();
            ViewBag.OrderList = new SelectList(list, "OrderId", "OrderId");

            if (ModelState.IsValid)
            {
                
                string subject = "Refund Request Confirmation";
                string body = "Your request for a refund was recieved.<br><br>" +
                    "The manager will review your request and you will have a response within 3-5 business days.";
                string emailID = Convert.ToString(TempData["email"]);

                WebMail.Send(emailID, subject, body, null, null, null, true, null, null, null, null, null, null);

                tblRefund.RefundRequestDate = DateTime.Now;
                tblRefund.Image = Image.FileName.ToString();
                tblRefund.RefundStatus = tblRefund.checkStatus();

                var folder = Server.MapPath("~/Uploads/");
                Image.SaveAs(Path.Combine(folder, Image.FileName.ToString()));

                db.tblRefunds.Add(tblRefund);
                db.SaveChanges();

                var order = db.tblOrders.FirstOrDefault(o => o.OrderId == tblRefund.OrderId);
                if (order != null)
                {
                    order.RefundStatus = tblRefund.RefundStatus;
                    db.SaveChanges();
                }


                return RedirectToAction("Refund", "Home", new { id = @Session["uid"] });
            }

            return View(tblRefund);
        }

        // GET: tblRefunds/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRefund tblRefund = db.tblRefunds.Find(id);
            if (tblRefund == null)
            {
                return HttpNotFound();
            }
            return View(tblRefund);
        }

        // POST: tblRefunds/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "RefundId,EmailID,OrderId,RefundRequestDate,RefundReason,Image,RefundStatus")] tblRefund tblRefund)
        {
            if (ModelState.IsValid)
            {
                var originalRefund = db.tblRefunds.Find(tblRefund.RefundId);
                TempData["e"] = originalRefund.EmailID;
                if (originalRefund != null)
                {
                    bool statusChanged = originalRefund.RefundStatus != tblRefund.RefundStatus;

                    originalRefund.RefundStatus = tblRefund.RefundStatus;

                    db.Entry(originalRefund).State = EntityState.Modified;
                    db.SaveChanges();

                    if (statusChanged)
                    {
                        var order = db.tblOrders.FirstOrDefault(o => o.OrderId == tblRefund.OrderId);
                        if (order != null)
                        {
                            order.RefundStatus = tblRefund.RefundStatus;
                            db.Entry(order).State = EntityState.Modified;
                            db.SaveChanges();
                        }

                        string emailSubject;
                        string emailBody;
                        string orderNum = originalRefund.OrderId.ToString();
                        

                        if (tblRefund.RefundStatus == "Successful")
                        {
                            emailSubject = "Refund Request Approved";
                            emailBody = "Dear Turbo Meals customer,<br><br>Your refund request for Order Number #"+orderNum+" has been approved.<br><br> Please note your refund will be processed soon.";
                        }
                        else if (tblRefund.RefundStatus == "Unsuccessful")
                        {
                            emailSubject = "Refund Request Denied";
                            emailBody = "Dear Turbo Meals customer,<br><br>We regret to inform you that your refund request for Order Number # "+orderNum+" has been denied.<br><br>For any further queries please send a reply to this email and we will gladly get back to you within 24 hours.";
                        }
                        else
                        {
                            // Handle other refund status values if needed
                            return RedirectToAction("Index");
                        }

                        // Send email to the user
                        string emailID = Convert.ToString(TempData["e"]);
                       
                        WebMail.Send(emailID, emailSubject, emailBody, null, null, null, true, null, null, null, null, null, null);
                    }
                }

                return RedirectToAction("Index");
            }

            return View(tblRefund);
        }



        // GET: tblRefunds/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblRefund tblRefund = db.tblRefunds.Find(id);
            if (tblRefund == null)
            {
                return HttpNotFound();
            }
            return View(tblRefund);
        }

        // POST: tblRefunds/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblRefund tblRefund = db.tblRefunds.Find(id);
            db.tblRefunds.Remove(tblRefund);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ShoppingCartMVC/Views/tblRefunds/Create.cshtml
@model ShoppingCartMVC.Models.tblRefund
<head>
    <title>Refund Request</title>
    <style>
        h1{
            text-align:center;
        }
        .card {
            border: 2px solid grey;
        }

        .custom-orange-button {
            background-color: orange; /* Set your desired shade of orange */
            color: white; /* Set the text color to contrast with the background */
            font-size: 20px; /* Set the font size to your preference */
            font-weight: bold; /* Make the text bold if desired */
            border: none;
        }

            .custom-orange-button:hover {
                background-color: darkorange;
                color: white;
            }

        .btn-dark {
            font-size: 20px;
            font-weight: bold;
        }
    </style>
</head>

<br />
<br />
<h1 class="card-title" style="text-align:center"><u>Submit Refund Request</u></h1>
<br />
<div class="col-lg-5 grid-margin stretch-card mx-auto">
    <div class="card">
        <div class="card-body">

            @using (Html.BeginForm("Create", "tblRefunds", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">

                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    <p> Email Address: &ensp;&ensp;&ensp;<b>@Html.DisplayFor(model => model.EmailID, new { htmlAttributes = new { @class = "form-control" } })</b></p>
                    @*sem 2 changes*@
                </div>
                <br />
                @Html.HiddenFor(model => model.OrderId, new { @Value = Request.QueryString["orderId"] })


                <div class="form-group">
                    Refund Reason
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RefundReason, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RefundReason, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">
                    <span>Select Image:</span>
                    <input type="file" name="Image" />
                </div>

                <br />
                <div class="form-group" style="text-align:center;">

                    <input type="submit" value="Submit" class="btn custom-orange-button  py-3 px-5" style="display: inline-block;" />
                    <p style="display: inline; margin-left: 10px;">
                        <a href="@Url.Action("Refund","Home",new {id=@Session["uid"]})" class="btn btn-dark  py-3 px-5">Back</a>
                    </p>
                </div>


            </div>
            }
        </div>
    </div>
</div>
<br />
<br />

ShoppingCartMVC/Views/tblRefunds/Delete.cshtml
@model ShoppingCartMVC.Models.tblRefund

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblRefund</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundRequestDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundRequestDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundReason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundReason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Image)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundStatus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShoppingCartMVC/Views/tblRefunds/Details.cshtml
@model ShoppingCartMVC.Models.tblRefund

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tblRefund</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.OrderId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrderId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundRequestDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundRequestDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundReason)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundReason)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Image)
        </dt>

        <dd>
            <img src="@Url.Content("~/Uploads/" + Model.Image)" alt="Image" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RefundStatus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RefundStatus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.RefundId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ShoppingCartMVC/Views/tblRefunds/Edit.cshtml
@model ShoppingCartMVC.Models.tblRefund


<head>
    <title>Refund Request Reply</title>
    <style>
        .card {
            border: 2px solid grey;
        }
        .custom-orange-button {
            background-color: orange; /* Set your desired shade of orange */
            color: white; /* Set the text color to contrast with the background */
            font-size: 20px; /* Set the font size to your preference */
            font-weight: bold; /* Make the text bold if desired */
            border: none;
        }

            .custom-orange-button:hover {
                background-color: darkorange;
                color: white;
            }

        .btn-dark {
            font-size: 20px;
            font-weight: bold;
        }
    </style>
</head>

<br />
<br />
<h1 class="card-title" style="text-align:center"><u>Refund Request Reply</u></h1>
<div class="col-lg-5 grid-margin stretch-card mx-auto">
    <div class="card">
        <div class="card-body">
            

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

        <div class="form-horizontal">

            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.RefundId)

            <div class="form-group">

                <div class="col-md-10">
                    Order Number: <b> #@Html.DisplayFor(model => model.OrderId, new { htmlAttributes = new { @class = "form-control" } })</b>
                    @Html.ValidationMessageFor(model => model.OrderId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    Email Address: <b>@Html.DisplayFor(model => model.EmailID, new { htmlAttributes = new { @class = "form-control" } })</b>
                    @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    Refund Request Date:  <b>@Html.DisplayFor(model => model.RefundRequestDate, new { htmlAttributes = new { @class = "form-control" } })</b>
                    @Html.ValidationMessageFor(model => model.RefundRequestDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    Refund Reason: <b>@Html.DisplayFor(model => model.RefundReason, new { htmlAttributes = new { @class = "form-control" } })</b>
                    @Html.ValidationMessageFor(model => model.RefundReason, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-10">
                    Image Proof:
                    <img src="~/Uploads/@Model.Image" style="width:150px; height:100px;" />
                </div>
            </div>

            <div class="form-group">

                <div class="card col-lg-9 grid-margin">
                    <div class="card-body">
                        <p style="text-align:center;"><b>Refund Status: </b></p>
                        <p>@Html.RadioButtonFor(s => s.RefundStatus, "Successful") Accept Request</p>
                        <p>@Html.RadioButtonFor(s => s.RefundStatus, "Unsuccessful") Decline Request</p>
                    </div>
                </div>
            </div>
            <br />

            <div class="form-group" style="text-align:center;">

                <input type="submit" value="Send Reply" class="btn custom-orange-button  py-3 px-5" style="display: inline-block;" />
                <p style="display: inline; margin-left: 10px;">
                    <a href="@Url.Action("Index","tblRefunds")" class="btn btn-dark  py-3 px-5">Back</a>
                </p>
            </div>

           
        </div>
            }

           
        </div>
     </div>
</div>
<br />
<br />

ShoppingCartMVC/Views/tblRefunds/Index.cshtml
@model IEnumerable<ShoppingCartMVC.Models.tblRefund>

<head>
    <title>All Refund Request</title>
    <style>
        h1{
            text-align:center;
        }

        .btn-success {
            font-size: 20px;
            font-weight: bold;
        }

        .btn-info {
            font-size: 20px;
            font-weight: bold;
        }
    </style>
</head>

<br />
<h1> All Refunds</h1>
<br />
<table class="table">
    <tr>
        <th>
            Order ID
        </th>
        <th>
           Email
        </th>
        <th>
            Request Date
        </th>
        <th>
           Refund Reason
        </th>
        <th>
            Image Proof
        </th>
        <th>
            Refund Status
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            #@Html.DisplayFor(modelItem => item.OrderId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RefundRequestDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RefundReason)
        </td>
        <td>
            <img src="~/Uploads/@item.Image" style="width:150px; height:100px;" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.RefundStatus)
        </td>
        <td>
            @if (item.RefundStatus == "Refund Requested")
            {
                <a href="@Url.Action("Edit","tblRefunds",new { id = item.RefundId })" class="btn btn-info">Reply</a>
            }
            else
                {
                    <span class="btn btn-success">Complete</span>
                }

        </td>
    </tr>
}

</table>
<br />