ShoppingCartMVC/Controllers/SupplierController.cs
using ShoppingCartMVC.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShoppingCartMVC.Controllers
{
    public class SupplierController : Controller
    {
        dbOnlineStoreEntities db=new dbOnlineStoreEntities();

        #region Showing Suppliers for Prep Staff

        public ActionResult Index()
        {
            var query = db.tblSuppliers.ToList();

            return View(query);
        }

        #endregion


        #region Add Suppliers

        public ActionResult Create()
        {
            var ingredients = db.tblIngredients
       .ToList() // Materialize the data
       .Select(m => new
       {
           ingName = m.Ing_Name,

       })
       .ToList();

            // Perform the conversion in-memory
            var ingrViewModel = ingredients.Select(m => new IngrVM
            {
                IngName = m.ingName,

            })
            .ToList();



            ViewBag.IngrNames = ingrViewModel;
            return View();
        }

        [HttpPost]
        public ActionResult Create(tblSupplier c,string supplType, string Active, string[] selectedIngrs, Dictionary<string, string> unitCosts)
        {
            if (ModelState.IsValid)
            {
                tblSupplier supp = new tblSupplier();
                supp.SupplName = c.SupplName;
                supp.SupplType = supplType;
                supp.ContactPerson = c.ContactPerson;
                supp.ContactPersonPos = c.ContactPersonPos;
                supp.ContactNum = c.ContactNum;
                supp.Email = c.Email;
                supp.Tel = c.Tel;
                supp.CompanyRegNum = c.CompanyRegNum;
                supp.PhysicalAddress = c.PhysicalAddress;
                supp.Active = Active;
                db.tblSuppliers.Add(supp);

                foreach (var ingrName in selectedIngrs)
                {
                    var ingredient = db.tblIngredients.FirstOrDefault(i => i.Ing_Name == ingrName);
                    if (ingredient != null)
                    {
                        double unitCost = 0;
                        if (unitCosts.ContainsKey(ingrName))
                        {
                            double.TryParse(unitCosts[ingrName], out unitCost);
                        }

                        var ingredientProduct = new SupplierIngredients
                        {
                            SupplierId = supp.SupplierId,
                            Ing_ID = ingredient.Ing_ID,

                            Ing_UnitCost = unitCost
                        };


                        db.SupplierIngredients.Add(ingredientProduct);


                    }
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                TempData["msg"] = "Supplier Not Inserted ";
            }
            return View();
        }

        #endregion


        #region Edit Supplier

        public ActionResult Edit(int id)
        {
            var query = db.tblSuppliers.SingleOrDefault(m => m.SupplierId == id);

            List<tblIngredients> allIngredients = db.tblIngredients.ToList();

            List<int> selectedIngredientIds = db.SupplierIngredients
        .Where(ip => ip.SupplierId == id)
        .Select(ip => ip.Ing_ID)
        .ToList();



            ViewBag.AllIngredients = allIngredients;
            ViewBag.SelectedIngredientIds = selectedIngredientIds;

            return View(query);
        }

        [HttpPost]
        public ActionResult Edit(tblSupplier c, int[] selectedIngrs)
        {
            try
            {

                db.Entry(c).State = EntityState.Modified;

                var existingIngredients = db.SupplierIngredients.Where(ip => ip.SupplierId == c.SupplierId);
                db.SupplierIngredients.RemoveRange(existingIngredients);

                // Add selected ingredients to the product
                if (selectedIngrs != null)
                {
                    foreach (var ingredientId in selectedIngrs)
                    {
                        db.SupplierIngredients.Add(new SupplierIngredients
                        {
                            SupplierId = c.SupplierId,
                            Ing_ID = ingredientId,

                        });
                    }
                }

                db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["msg"] = ex;
            }
            return RedirectToAction("Index");
        }

        #endregion

        #region Delete Supplier

        public ActionResult Delete(int id)
        {
            var query = db.tblSuppliers.SingleOrDefault(m => m.SupplierId == id);
            db.tblSuppliers.Remove(query);
            db.SaveChanges();
            return RedirectToAction("Index");
        }



        #endregion

        #region Supplier Details
        public ActionResult Details(int id)
        {
            var selectedIngredients = db.SupplierIngredients
     .Where(ip => ip.SupplierId == id)
     .Join(db.tblIngredients, ip => ip.Ing_ID, ing => ing.Ing_ID, (ip, ing) => ing.Ing_Name)
     .ToList();

            ViewBag.SelectedIngredientNames = selectedIngredients;
            var query = db.tblSuppliers.SingleOrDefault(m => m.SupplierId == id);
            return View(query);
        }
        #endregion


    }
}

ShoppingCartMVC/Views/Supplier/Create.cshtml
@model ShoppingCartMVC.Models.tblSupplier
<head>
    <title>Add Supplier</title>
    <style>
        .card {
            border: 2px solid grey;
        }

        .form-group {
            text-align: center;         
        }

        .checkbox-grid {
            display: grid;
            grid-template-columns: repeat(3, 2fr); /* Adjust the number of columns as needed */
            gap: 10px; /* Adjust the gap between checkboxes */
        }

        input[type="checkbox"] {
            width: 20px; /* Adjust the width to make the checkbox wider */
            height: 20px; /* Adjust the height to make the checkbox taller */
        }

        .custom-orange-button {
            background-color: orange; /* Set your desired shade of orange */
            color: white; /* Set the text color to contrast with the background */
            font-size: 20px; /* Set the font size to your preference */
            font-weight: bold; /* Make the text bold if desired */
            border: none;
        }

            .custom-orange-button:hover {
                background-color: darkorange;
                color: white;
            }

        .btn-dark {
            font-size: 20px;
            font-weight: bold;
        }
    </style>
</head>
<br />

<h1 class="card-title" style="text-align:center"><u> Add Supplier </u></h1>
<div class="col-sm-7 mx-auto">
    <div class="card">
        <div class="card-body">
            <br />
            <h3 style="color:red;">@TempData["msg"]</h3>
            @using (Html.BeginForm())
            {


                <form class="bg-white p-5 contact-form">
                    <div class="form-group">
                        <span>Supplier Name:</span>
                        @Html.TextBoxFor(m => m.SupplName, new { @class = "form-control" })
                    </div>

                    <div class="form-group">

                        <label for="state">Supplier Type:</label>
                        <select name="supplType">
                            <option value="" disabled selected></option>
                            <option value="Produce">Produce</option>
                            <option value="Bakery">Bakery </option>
                            <option value="Beverage">Beverage</option>
                            <option value="Dairy">Dairy</option>
                            <option value="Meat">Meat</option>
                            <option value="Condiments">Condiments</option>
                            <option value="General">General</option>
                            @*<option value="EC">Eastern Cape</option>
                <option value="NC">Northern Cape</option>
                <option value="FS">Free State</option>*@


                        </select>
                    </div>

                    <div class="form-group">
                        <span>Contact Person:</span>
                        @Html.TextBoxFor(m => m.ContactPerson, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <span>Contact Person Position:</span>
                        @Html.TextBoxFor(m => m.ContactPersonPos, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <span>Contact Number:</span>
                        @Html.TextBoxFor(m => m.ContactNum, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <span>Email:</span>
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <span> Telephone:</span>
                        @Html.TextBoxFor(m => m.Tel, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <span>Company Registration Number:</span>
                        @Html.TextBoxFor(m => m.CompanyRegNum, new { @class = "form-control" })
                    </div>

                    <div class="form-group">
                        <span> Physical Address:</span>
                        @Html.TextBoxFor(m => m.PhysicalAddress, new { @class = "form-control" })
                    </div>

                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <span class="card-title">Active:</span>
                                <br />
                                <input type="radio" name="Active" value="Yes" /><label>&ensp;Yes</label>
                                <br />
                                <input type="radio" name="Active" value="No" /><label>&ensp; No</label>

                            </div>
                        </div>
                    </div>

                    <br />
                    <div class="checkbox-grid">
                        <h4>Ingredients To be Supplied:</h4>
                        <br />
                        <br />
                        @foreach (var ing in ViewBag.IngrNames)
                        {
                            <div class="form-group">
                                <label>
                                    <input type="checkbox" name="selectedIngrs[]" value="@ing.IngName" />
                                    @ing.IngName
                                </label>
                                <br />
                                <span>Unit Cost:</span>
                                <input type="text" name="unitCosts[@ing.IngName]" />

                            </div>

                        }


                    </div>

                    <br />
                    <div class="form-group" style="text-align:center;">

                        <input type="submit" value="Add" class="btn custom-orange-button  py-3 px-5" style="display: inline-block;" />
                        <p style="display: inline; margin-left: 10px;">
                            <a href="@Url.Action( "Index","Supplier")" class="btn btn-dark  py-3 px-5">Back</a>
                        </p>
                    </div>
                   
                </form>



            }

            
        </div>
    </div>
</div>

<br />
<br />
<br />

ShoppingCartMVC/Views/Supplier/Details.cshtml
@model ShoppingCartMVC.Models.tblSupplier

<head>
    <title> Supplier Details</title>
    <style>
        .card {
            border: 2px solid grey;
        }

        .form-group {
            text-align: center;
        }

        .checkbox-grid {
            display: grid;
            grid-template-columns: repeat(3, 2fr); /* Adjust the number of columns as needed */
            gap: 10px; /* Adjust the gap between checkboxes */
        }

        .orange-link {
            color: orange;
            font-size: 25px !important; /* Increase the font size to your desired value */
            font-weight: bold; /* Make the text bold */
            text-decoration: none; /* Remove the underline (if needed) */
        }

            .orange-link:hover {
                color: orangered;
            }

        a {
            color: orange;
            font-size: 25px !important; /* Increase the font size to your desired value */
            font-weight: bold; /* Make the text bold */
            text-decoration: none;
        }
    </style>
</head>
<br />

<h1 class="card-title" style="text-align:center"><u> Supplier Details</u></h1>
<div class="col-sm-7 mx-auto">
    <div class="card">
        <div class="card-body">
            <dd>
                
                <dl class="dl-horizontal">
                    <dt>
                        <span style="display: inline-block; color: cadetblue;">Supplier Name:</span>
                        @Html.DisplayFor(model => model.SupplName)
                    </dt>

                    <dd>
                        <span style="display: inline-block; color: cadetblue;"> <b>Supplier Type: </b></span>
                        &ensp; @Html.DisplayFor(model => model.SupplType)
                    </dd>

                    <dt>
                        <span style="display: inline-block; color: cadetblue;">Contact Person:</span>
                        &ensp; @Html.DisplayFor(model => model.ContactPerson)
                    </dt>

                    <dd>
                        <span style="display: inline-block; color: cadetblue;"> <b>Contact Person Position: </b></span>
                        @Html.DisplayFor(model => model.ContactPersonPos)
                    </dd>
                    <dd>
                        <span style="display: inline-block; color: cadetblue;"> <b>Contact Number: </b></span>
                        &ensp;  @Html.DisplayFor(model => model.ContactNum)
                    </dd>
                    <dd>
                        <span style="display: inline-block; color: cadetblue;"> <b>Email: </b></span>
                        &ensp;  @Html.DisplayFor(model => model.Email)
                    </dd>
                    <dd>
                        <span style="display: inline-block; color: cadetblue;"> <b>Telephone: </b></span>
                        &ensp;  @Html.DisplayFor(model => model.Tel)
                    </dd>
                    <dd>
                        <span style="display: inline-block; color: cadetblue;"> <b> Company Registration Number: </b></span>
                        &ensp; @Html.DisplayFor(model => model.CompanyRegNum)
                    </dd>
                    <dd>
                        <span style="display: inline-block; color: cadetblue;"> <b>Physical Address: </b></span>
                        &ensp;  @Html.DisplayFor(model => model.PhysicalAddress)
                    </dd>
                    <dd>
                        <span style="display: inline-block; color: cadetblue;"> <b>Active: </b></span>
                        &ensp;  @Html.DisplayFor(model => model.Active)
                    </dd>
                    <hr />
                    <dd>
                        <h4 style="text-align:center">Ingredients being Supplied:</h4>
                        @foreach (var ingredientName in ViewBag.SelectedIngredientNames)
                        {
                            <p>@ingredientName</p>
                        }
                    </dd>
                </dl>

                <p style="text-align:center">

                    @*<a href="@Url.Action("Index", "AdminHome",new {id=Model.SupplierId})">Order Ingredients</a>|*@
                    @Html.ActionLink("Edit", "Edit", new { id = Model.SupplierId },new { @class = "orange-link" }) |
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "orange-link" })
                </p>
        </div>
    </div>
</div>

<br />
<br />
<br />

ShoppingCartMVC/Views/Supplier/Edit.cshtml
@model ShoppingCartMVC.Models.tblSupplier

<head>
    <title>Update Supplier</title>
    <style>
        .card {
            border: 2px solid grey;
        }

        .form-group {
            text-align: center;
        }

        .checkbox-grid {
            display: grid;
            grid-template-columns: repeat(3, 2fr); /* Adjust the number of columns as needed */
            gap: 10px; /* Adjust the gap between checkboxes */
        }

        input[type="checkbox"] {
            width: 20px; /* Adjust the width to make the checkbox wider */
            height: 20px; /* Adjust the height to make the checkbox taller */
        }

        .custom-orange-button {
            background-color: orange; /* Set your desired shade of orange */
            color: white; /* Set the text color to contrast with the background */
            font-size: 20px; /* Set the font size to your preference */
            font-weight: bold; /* Make the text bold if desired */
            border: none;
        }

            .custom-orange-button:hover {
                background-color: darkorange;
                color: white;
            }

        .btn-dark {
            font-size: 20px;
            font-weight: bold;
        }
    </style>
</head>
<br />

<h1 class="card-title" style="text-align:center"><u> Update Supplier </u></h1>
<div class="col-sm-7 mx-auto">
    <div class="card">
        <div class="card-body">
            <br />
            <h3 style="color:red;">@TempData["msg"]</h3>
            @using (Html.BeginForm())
            {

                <div class="form-horizontal">


                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.SupplierId)

                    <div class="form-group">
                        Supplier Name:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SupplName, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        Supplier Type:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SupplType, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        Supplier Contact Person:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ContactPerson, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        Supplier Contact Person Position:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ContactPersonPos, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        Contact Number:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ContactNum, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        Email:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        Telephone:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Tel, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        Company Registration Number:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CompanyRegNum, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        Physical Address:
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhysicalAddress, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Active, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Active, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>
                    <br />


                    <div class="checkbox-grid">
                        <h4>Ingredients:</h4>
                        @foreach (var ing in ViewBag.AllIngredients)
                        {

                            <div class="form-group">
                                <label>
                                    <input type="checkbox" name="selectedIngrs[]" value="@ing.Ing_ID" @(ViewBag.SelectedIngredientIds.Contains(ing.Ing_ID) ? "checked" : "") />
                                    @ing.Ing_Name
                                </label>
                                <br />
                            </div>
                        }
                    </div>
                    <br />

                    <div class="form-group">
                       
                    </div>

                    <div class="form-group" style="text-align:center;">

                        <input type="submit" value="Update" class="btn custom-orange-button  py-3 px-5" style="display: inline-block;" />
                        <p style="display: inline; margin-left: 10px;">
                            <a href="@Url.Action( "Index","Supplier")" class="btn btn-dark  py-3 px-5">Back</a>
                        </p>
                    </div>
                </div>

            }

            

        </div>
    </div>
</div>

<br />
<br />
<br />

ShoppingCartMVC/Views/Supplier/Index.cshtml
@model IEnumerable<ShoppingCartMVC.Models.tblSupplier>

<head>
    <title>Suppliers List</title>
    <style>
        h1{
            text-align:center;
        }

        .btn-danger {
            font-size: 20px;
            font-weight: bold;
        }

        .btn-info {
            font-size: 20px;
            font-weight: bold;
        }
    </style>
</head>
<script src="~/js/jquery.min.js"></script>

<script>
    $(document).ready(function () {
        $("#searchBox").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>

<br />
<h1>All Suppliers</h1>
<div class="container">

    <div class="form-group">
        <input type="text" class="form-control col-lg-4 ml-auto" placeholder="Search Here" id="searchBox" />
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Type</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.SupplierId</td>
                    <td>@item.SupplName</td>
                    <td>@item.SupplType</td>
                    <td>

                        <a href="@Url.Action("Details", "Supplier", new { id = item.SupplierId})" class="btn btn-info">Details</a>

                        <a href="@Url.Action("Edit", "Supplier", new { id = item.SupplierId})" class="btn btn-info">Edit</a>
                        <a href="@Url.Action("Delete", "Supplier", new { id = item.SupplierId})" class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>


</div>
<br />
<br />