ShoppingCartMVC/Controllers/DonationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using ShoppingCartMVC.Models;

namespace ShoppingCartMVC.Controllers
{
    public class DonationsController : Controller
    {
        private dbOnlineStoreEntities db = new dbOnlineStoreEntities();

        #region User Donation Index
        // GET: Donations
        public ActionResult Index()
        {
            int sum = 0;

            try
            {
                sum = db.tblDonations.Select(t => t.DonationAmount).Sum();
            }catch(Exception e)
            {
                //catch null error
            }
            ViewBag.TotalDonations = 106422 + sum;
            return View(db.tblDonations.ToList());
        }
        #endregion

        #region Donation Details Admin
        // GET: Donations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDonations tblDonations = db.tblDonations.Find(id);
            if (tblDonations == null)
            {
                return HttpNotFound();
            }
            return View(tblDonations);
        }
        #endregion

        #region Make Donation
        // GET: Donations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Donations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DonationId,DonCharityOrg,DonEmail,DonationAmount")] tblDonations tblDonations)
        {
            if (ModelState.IsValid)
            {
                db.tblDonations.Add(tblDonations);
                db.SaveChanges();
              int amt=  tblDonations.DonationAmount;

                return Content("<script>" +
                        "function callPayPal() {" +
                        "window.location.href = 'https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_xclick&amount=" + amt.ToString() + "&business=sb-w3cyw20367505@business.example.com&item_name=Donation&return=https://2023grp01a.azurewebsites.net/Donations/DonationSuccess';" +
                        "}" +
                        "callPayPal();" +
                        "</script>");
            }

            return View(tblDonations);
        }
        #endregion

        public ActionResult DonationSuccess()
        {
            return View();
        }

        #region Donation List Admin
        public ActionResult DonationDetails()
        {
            var query = db.tblDonations.ToList();
            return View(query);
        }
        #endregion

        #region Edit
        // GET: Donations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDonations tblDonations = db.tblDonations.Find(id);
            if (tblDonations == null)
            {
                return HttpNotFound();
            }
            return View(tblDonations);
        }

      
        // POST: Donations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DonationId,DonCharityOrg,DonEmail,DonationAmount")] tblDonations tblDonations)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblDonations).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblDonations);
        }
        #endregion

        #region Delete
        // GET: Donations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblDonations tblDonations = db.tblDonations.Find(id);
            if (tblDonations == null)
            {
                return HttpNotFound();
            }
            return View(tblDonations);
        }

        // POST: Donations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblDonations tblDonations = db.tblDonations.Find(id);
            db.tblDonations.Remove(tblDonations);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
    }
}

ShoppingCartMVC/Views/Donations/Create.cshtml
@model ShoppingCartMVC.Models.tblDonations
<head>
    <title>Make Donation</title>

    <style>
        .card {
            border: 2px solid grey;
            text-align: center;
        }

        h1 {
            text-align: center;
            background-color: rgb(255, 106, 0);
            color: #fff;
            margin: 0;
            padding: 15px;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }

        .custom-orange-button {
            background-color: orange; /* Set your desired shade of orange */
            color: white; /* Set the text color to contrast with the background */
            font-size: 20px; /* Set the font size to your preference */
            font-weight: bold; /* Make the text bold if desired */
            border: none;
        }

            .custom-orange-button:hover {
                background-color: darkorange;
                color: white;
            }

        .btn-dark {
            font-size: 20px;
            font-weight: bold;
        }
    </style>

</head>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h1 style="text-align:center">Make A Donation Today</h1>
        <br />
        <div class="col-sm-6 mx-auto">
            <div class="card">


                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <div class="col-md-10">
                        Select Donation Organization:
                        <br />

                        <div class="r-md-10">

                            @Html.RadioButtonFor(model => model.DonCharityOrg, "Village of Peace")
                            Village of Peace
                        </div>
                        <div class="r-md-10">

                            @Html.RadioButtonFor(model => model.DonCharityOrg, "Meals on Wheels")
                            Meals on Wheels
                        </div>
                        <div class="r-md-10">

                            @Html.RadioButtonFor(model => model.DonCharityOrg, "World Food Program")
                            World Food Program
                        </div>
                        @Html.ValidationMessageFor(model => model.DonCharityOrg, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">

                    <div class="col-md-10">
                        Your Email Address
                        @Html.EditorFor(model => model.DonEmail, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DonEmail, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group">

                    <div class="col-md-10">
                        Donation Amount
                        @Html.EditorFor(model => model.DonationAmount, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DonationAmount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <br />
                <div class="form-group" style="text-align:center;">

                    <input type="submit" value="Make Donation" class="btn custom-orange-button  py-3 px-5" style="display: inline-block;" />
                    <p style="display: inline; margin-left: 10px;">
                        <a href="@Url.Action( "Index","Donations")" class="btn btn-dark  py-3 px-5">Back</a>
                    </p>
                </div>


            </div>
        </div>
    </div>
}


<br /><br />

ShoppingCartMVC/Views/Donations/Delete.cshtml
@model ShoppingCartMVC.Models.tblDonations

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tblDonations</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DonCharityOrg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonCharityOrg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DonationAmount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DonationAmount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ShoppingCartMVC/Views/Donations/Details.cshtml
@model ShoppingCartMVC.Models.tblDonations
<head>
    <title>
        Donation Details
    </title>
    <style>
        .card {
            border: 2px solid grey;
            text-align:center
        }

        h1 {
            text-align: center;
            background-color: rgb(255, 106, 0);
            color: #fff;
            margin: 0;
            padding: 15px;
            border-top-left-radius: 10px;
            border-top-right-radius: 10px;
        }

        .orange-link {
            font-size: 20px;
            font-weight: bold;
         
        }
    </style>
</head>
@{
    ViewBag.Title = "Details";
}

<h1 style="text-align:center" >Donation Details</h1>
<br />
<div class="col-md-6 mx-auto">
    <hr />
    <div class="card mx-auto">


        <dl class="dl-v">
            <dt>
                Oraginzation Donated Too:
            </dt>

            <dd>@Html.DisplayFor(model => model.DonCharityOrg)</dd>

            <dt>
                Donator's Email:
            </dt>

            <dd> @Html.DisplayFor(model => model.DonEmail) </dd>

            <dt>
                Donation Amount:
            </dt>

            <dd>R @Html.DisplayFor(model => model.DonationAmount) </dd>

        </dl>
        <p>
            @Html.ActionLink("Back to List", "DonationDetails", null, new { @class = "orange-link" })
        </p>
    </div>
</div>

<br />
<br />

ShoppingCartMVC/Views/Donations/DonationDetails.cshtml
@model IEnumerable<ShoppingCartMVC.Models.tblDonations>
@{
    ViewBag.Title = "DonationDetails";
}
<head>
    <title>Donations List</title>
    <style>
        h1{
            text-align:center;
        }
        .orange-link {
            color: orange;
            font-size: 20px; /* Increase the font size to your desired value */
            font-weight: bold; /* Make the text bold */
            text-decoration: none; /* Remove the underline (if needed) */
        }

            .orange-link:hover {
                color: orangered;
            }

    </style>
</head>

<br />
<h1>Donation List</h1>
<br />
<br />
<table class="table">
    <tr>
        <th>
            Donation Organization
        </th>
        <th>
            Email
        </th>
        <th>
            Donation Amount
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DonCharityOrg)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonEmail)
            </td>
            <td>
                R @Html.DisplayFor(modelItem => item.DonationAmount)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.DonationId }, new { @class = "orange-link" })
            </td>
        </tr>
    }

</table>
<br />
<br />

ShoppingCartMVC/Views/Donations/DonationSuccess.cshtml
<head>
    <title>Donation Successful</title>
    <style>
        .card {
            border: 3px solid grey;
        }
    </style>
</head>

<br />
<div class="card mx-auto" style="max-width: fit-content;">
    <div class="row no-gutters">
        <div class="col-md-6">
            <div class="card-body">
                <h1 class="card-title">Donation Made Successfully!</h1>
                <h3 class="card-text"> Thank you for your contribution.</h3>
                <p class="card-text">Please <b> @Html.ActionLink("Click Here", "Index", "Home")</b>  to return back to Turbo Meals Home.  </p>

            </div>
        </div>
        <div class="col-md-6">

            <img src="~/Images/donate8.jpg" class="card-img" alt="..." />
        </div>
    </div>
</div>

<br />

ShoppingCartMVC/Views/Donations/Edit.cshtml
@model ShoppingCartMVC.Models.tblDonations

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tblDonations</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DonationId)

        <div class="form-group">
            @Html.LabelFor(model => model.DonCharityOrg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonCharityOrg, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonCharityOrg, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DonationAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DonationAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DonationAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ShoppingCartMVC/Views/Donations/Index.cshtml
@model IEnumerable<ShoppingCartMVC.Models.tblDonations>

<head>
    <title>
        Donations
    </title>
</head>


<style>
    h1 {
        text-align: center;
        background-color: rgb(255, 106, 0);
        color: #fff;
        margin: 0;
        padding: 15px;
        border-top-left-radius: 10px;
        border-top-right-radius: 10px;
    }
    .box {
        display: flex; /* always present for Flexbox practices */
        flex-direction: row; /* elements stack */
        justify-content: center;
        flex-wrap: wrap;
        margin-bottom: 20px;
    }

        .box > * {
            flex: 1 20vw;
            /*flex-grow: 1;*/ /*Allow the element to grow if there is available space */
            /*flex-shrink: 1;*/ /*Elements shrink at the same rate */
            /*flex-basis: 100%;*/ /* Elements will cover the same amount, if is possible the 100% of the width */
            margin: 20px;
        }

    .boxStart {
        display: flex; /* always present for Flexbox practices */
        flex-direction: row; /* elements stack */
        flex-wrap: nowrap;
        flex-shrink: 1;
        flex-grow: 0;
    }

        .boxStart > * {
            flex: 1;
            flex-grow: 0;
            flex-shrink: 1;
            justify-content: center;
            /*flex-grow: 1;*/ /*Allow the element to grow if there is available space */
            /*flex-shrink: 1;*/ /*Elements shrink at the same rate */
            /*flex-basis: 100%;*/ /* Elements will cover the same amount, if is possible the 100% of the width */
            margin-inline: 5px;
        }

    .coverImage {
        object-fit: contain;
        width: 100%;
        height: 160px;
    }

    .ImageRoundBorders {
        --bs-card-inner-border-radius: calc(0.5rem - 1px);
        border-top-left-radius: var(--bs-card-inner-border-radius);
        border-top-right-radius: var(--bs-card-inner-border-radius);
        border-bottom-right-radius: var(--bs-card-inner-border-radius);
        border-bottom-left-radius: var(--bs-card-inner-border-radius);
    }

    .detailImage {
        object-fit: scale-down;
        width: 100%;
        height: 100%;
    }

    .btn-dark {
        font-size: 20px;
        font-weight: bold;
    }
</style>

<h1>Donations Home</h1>
<br />
<div  class="col-md-10">
    <h2>About Our Supported Charity Organizations: </h2>
</div>
<div class="box">
    <div class="card bg-primary" style="max-width: 20rem;">
        <div class="card-body">
            <h4 class="card-title text-white">Village of peace</h4>
            <div class="justify-content-center">
                <image src="@Url.Content("~/Images/Vop-logo-retina.png")" class="d-block user-select-none coverImage card-img-top bg-white" width="10px" height="10px" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle" />
            </div>
            <p class="card-body text-white">Help malnourished children in Afghanistan together with Village of Peace. For R50 we can help a child for one month. With your donation you contribute to a better future for children in Afghanistan</p>

        </div>
    </div>

    <div class="card bg-primary" style="max-width: 20rem;">
        <div class="card-body">
            <h4 class="card-title text-white">Meals On Wheels</h4>
            <div class="justify-content-center">
                <image src="@Url.Content("~/Images/mealsOnWheelsLogo.png")" class="d-block user-select-none coverImage card-img-top bg-white" width="10px" height="10px" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle" />
            </div>
            <p class="card-body text-white">Meals on Wheels is a multi-faceted welfare non-profit organization tasked with helping poverty-stricken South Africans with nutritious meals and food security.</p>

        </div>
    </div>

    <div class="card bg-primary" style="max-width: 20rem;">
        <div class="card-body">
            <h4 class="card-title text-white">World Food Program</h4>
            <div class="justify-content-center">
                <image src="@Url.Content("~/Images/WFPLogo.png")" class="d-block user-select-none coverImage card-img-top bg-white" width="10px" height="10px" focusable="false" role="img" preserveAspectRatio="xMidYMid slice" viewBox="0 0 318 180" style="font-size:1.125rem;text-anchor:middle" />
            </div>
            <p class="card-body text-white">We bring life-saving relief in emergencies and use food assistance to build a pathway to peace, stability and prosperity for people recovering from conflict, disasters and the impacts of climate change.</p>
        </div>
    </div>

    <div class="card bg-primary" style="max-width: 20rem;">
        <div class="card-body justify-content-center">
            <h3 class="card-title text-white">Our Total Donations This Month</h3>
            <div class="card bg-dark" style="max-width: 20rem;">
                <div class="card-body justify-content-center">
                    <h3 class="text-white">R @ViewBag.TotalDonations </h3>
                </div>

            </div>
            <br />
            <br />
            <div @*class="col-md-1 mx-auto"*@>
                <a class="btn btn-dark text-white" asp-controller="Donations" asp-action="Create" href="@Url.Action("Create","Donations")" )>Make Donation</a>
            </div>
        </div>
            </div>
        </div>

<p></p>

    @*<h2 class="bg-primary text-white">Your Donations</h2>*@
   
 <br />
<br />  